/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CollectionsImport } from './routes/collections'
import { Route as PageImport } from './routes/$page'
import { Route as IndexImport } from './routes/index'
import { Route as FavoritesIndexImport } from './routes/favorites/index'
import { Route as SearchLayoutImport } from './routes/search/_layout'
import { Route as ProductHandleImport } from './routes/product/$handle'
import { Route as SearchLayoutIndexImport } from './routes/search/_layout/index'
import { Route as SearchLayoutCollectionImport } from './routes/search/_layout/$collection'

// Create Virtual Routes

const SearchImport = createFileRoute('/search')()

// Create/Update Routes

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsRoute = CollectionsImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesIndexRoute = FavoritesIndexImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRoute,
} as any)

const SearchLayoutRoute = SearchLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => SearchRoute,
} as any)

const ProductHandleRoute = ProductHandleImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRoute,
} as any)

const SearchLayoutIndexRoute = SearchLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchLayoutRoute,
} as any)

const SearchLayoutCollectionRoute = SearchLayoutCollectionImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => SearchLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsImport
      parentRoute: typeof rootRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/search/_layout': {
      id: '/search/_layout'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLayoutImport
      parentRoute: typeof SearchRoute
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/_layout/$collection': {
      id: '/search/_layout/$collection'
      path: '/$collection'
      fullPath: '/search/$collection'
      preLoaderRoute: typeof SearchLayoutCollectionImport
      parentRoute: typeof SearchLayoutImport
    }
    '/search/_layout/': {
      id: '/search/_layout/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchLayoutIndexImport
      parentRoute: typeof SearchLayoutImport
    }
  }
}

// Create and export the route tree

interface SearchLayoutRouteChildren {
  SearchLayoutCollectionRoute: typeof SearchLayoutCollectionRoute
  SearchLayoutIndexRoute: typeof SearchLayoutIndexRoute
}

const SearchLayoutRouteChildren: SearchLayoutRouteChildren = {
  SearchLayoutCollectionRoute: SearchLayoutCollectionRoute,
  SearchLayoutIndexRoute: SearchLayoutIndexRoute,
}

const SearchLayoutRouteWithChildren = SearchLayoutRoute._addFileChildren(
  SearchLayoutRouteChildren,
)

interface SearchRouteChildren {
  SearchLayoutRoute: typeof SearchLayoutRouteWithChildren
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchLayoutRoute: SearchLayoutRouteWithChildren,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/collections': typeof CollectionsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/search': typeof SearchLayoutRouteWithChildren
  '/favorites': typeof FavoritesIndexRoute
  '/search/$collection': typeof SearchLayoutCollectionRoute
  '/search/': typeof SearchLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/collections': typeof CollectionsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/search': typeof SearchLayoutIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/search/$collection': typeof SearchLayoutCollectionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/collections': typeof CollectionsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/search': typeof SearchRouteWithChildren
  '/search/_layout': typeof SearchLayoutRouteWithChildren
  '/favorites/': typeof FavoritesIndexRoute
  '/search/_layout/$collection': typeof SearchLayoutCollectionRoute
  '/search/_layout/': typeof SearchLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/collections'
    | '/product/$handle'
    | '/search'
    | '/favorites'
    | '/search/$collection'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/collections'
    | '/product/$handle'
    | '/search'
    | '/favorites'
    | '/search/$collection'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/collections'
    | '/product/$handle'
    | '/search'
    | '/search/_layout'
    | '/favorites/'
    | '/search/_layout/$collection'
    | '/search/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  CollectionsRoute: typeof CollectionsRoute
  ProductHandleRoute: typeof ProductHandleRoute
  SearchRoute: typeof SearchRouteWithChildren
  FavoritesIndexRoute: typeof FavoritesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  CollectionsRoute: CollectionsRoute,
  ProductHandleRoute: ProductHandleRoute,
  SearchRoute: SearchRouteWithChildren,
  FavoritesIndexRoute: FavoritesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$page",
        "/collections",
        "/product/$handle",
        "/search",
        "/favorites/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$page": {
      "filePath": "$page.tsx"
    },
    "/collections": {
      "filePath": "collections.tsx"
    },
    "/product/$handle": {
      "filePath": "product/$handle.tsx"
    },
    "/search": {
      "filePath": "search",
      "children": [
        "/search/_layout"
      ]
    },
    "/search/_layout": {
      "filePath": "search/_layout.tsx",
      "parent": "/search",
      "children": [
        "/search/_layout/$collection",
        "/search/_layout/"
      ]
    },
    "/favorites/": {
      "filePath": "favorites/index.tsx"
    },
    "/search/_layout/$collection": {
      "filePath": "search/_layout/$collection.tsx",
      "parent": "/search/_layout"
    },
    "/search/_layout/": {
      "filePath": "search/_layout/index.tsx",
      "parent": "/search/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
