/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PageImport } from './routes/$page'
import { Route as IndexImport } from './routes/index'
import { Route as SearchLayoutImport } from './routes/search/_layout'
import { Route as SearchLayoutIndexImport } from './routes/search/_layout/index'

// Create Virtual Routes

const SearchImport = createFileRoute('/search')()

// Create/Update Routes

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchLayoutRoute = SearchLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => SearchRoute,
} as any)

const SearchLayoutIndexRoute = SearchLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/search/_layout': {
      id: '/search/_layout'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLayoutImport
      parentRoute: typeof SearchRoute
    }
    '/search/_layout/': {
      id: '/search/_layout/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchLayoutIndexImport
      parentRoute: typeof SearchLayoutImport
    }
  }
}

// Create and export the route tree

interface SearchLayoutRouteChildren {
  SearchLayoutIndexRoute: typeof SearchLayoutIndexRoute
}

const SearchLayoutRouteChildren: SearchLayoutRouteChildren = {
  SearchLayoutIndexRoute: SearchLayoutIndexRoute,
}

const SearchLayoutRouteWithChildren = SearchLayoutRoute._addFileChildren(
  SearchLayoutRouteChildren,
)

interface SearchRouteChildren {
  SearchLayoutRoute: typeof SearchLayoutRouteWithChildren
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchLayoutRoute: SearchLayoutRouteWithChildren,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/search': typeof SearchLayoutRouteWithChildren
  '/search/': typeof SearchLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/search': typeof SearchLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/search': typeof SearchRouteWithChildren
  '/search/_layout': typeof SearchLayoutRouteWithChildren
  '/search/_layout/': typeof SearchLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$page' | '/search' | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$page' | '/search'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/search'
    | '/search/_layout'
    | '/search/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  SearchRoute: typeof SearchRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  SearchRoute: SearchRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$page",
        "/search"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$page": {
      "filePath": "$page.tsx"
    },
    "/search": {
      "filePath": "search",
      "children": [
        "/search/_layout"
      ]
    },
    "/search/_layout": {
      "filePath": "search/_layout.tsx",
      "parent": "/search",
      "children": [
        "/search/_layout/"
      ]
    },
    "/search/_layout/": {
      "filePath": "search/_layout/index.tsx",
      "parent": "/search/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
